cloud_sources:
  - name: /narrow_stereo_textured/points2_filtered
    raw_name: /narrow_stereo_textured/points2
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: narrow_stereo_optical_frame
    sensor_stereo_other_frame: narrow_stereo_gazebo_r_stereo_camera_optical_frame
  - name: /tilt_scan_cloud_filtered2
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: laser_tilt_link

camera_info_topic: /narrow_stereo_textured/left/camera_info
camera_stereo_offset_left: 128
camera_stereo_offset_right: 0


