footprint_links:
  - name: base_link
  - name: r_upper_arm_link
  - name: r_shoulder_pan_link
  - name: r_shoulder_lift_link
  - name: r_forearm_link
  - name: r_gripper_palm_link
  - name: r_gripper_l_finger_link
  - name: r_gripper_l_finger_tip_link
  - name: r_gripper_r_finger_link
  - name: r_gripper_r_finger_tip_link
  - name: l_upper_arm_link
  - name: l_shoulder_pan_link
  - name: l_shoulder_lift_link
  - name: l_forearm_link
  - name: l_gripper_palm_link
  - name: l_gripper_l_finger_link
  - name: l_gripper_l_finger_tip_link
  - name: l_gripper_r_finger_link
  - name: l_gripper_r_finger_tip_link 

  
