#!/usr/bin/env bash
# 	wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
#	chmod 755 parallel
#	sudo ln -s ./parallel /usr/local/bin/parallel
#
# @author
#	Bharath Sankaran
#	Computational Motor Control and Learning Laboratory
#	University of Southern California
#	Los Angeles, CA 90089
#	12/04/2012
#
#


# object names:
declare -a TRAIN_EXAMPLES=(axe bigbox broom brush flowerspray gastank handlebottle heavyranch pan pipe shovel spadefork spraybottle watercan wreckbar apples bathroomkit bottles cups glasses vases)

#declare -a TRAIN_EXAMPLES=(vases)

vps_fname=$(rospack find vision_module)/data/tree_vps.txt

PLY_FILE_DIR=$(rospack find vision_compare)/data/ply_files
OMAP_SAVE_DIR=$(rospack find vision_compare)/database/conf_org
BUILD_OMAP=$(rospack find vision_module)/bin/compute_confmat

# read every number
#vps=( $(<"$vps_fname") )

# read line by line
idx=0
while read line; do
  vps[$idx]=$line
  idx=$((idx+1))
done < "$vps_fname"

# call parallel for the train examples
(
for tidx in "${!TRAIN_EXAMPLES[@]}"; do
	for vidx in "${!vps[@]}"; do
		echo "${BUILD_OMAP} ${PLY_FILE_DIR}/${TRAIN_EXAMPLES[$tidx]}.ply $tidx ${OMAP_SAVE_DIR} ${vps[$vidx]} $vidx";
	done
done
) | parallel

# combine the files into only one
for tidx in "${!TRAIN_EXAMPLES[@]}"; do
	for vidx in "${!vps[@]}"; do
		cat ${OMAP_SAVE_DIR}/confMatorg_${tidx}_${vidx}.txt >> ${OMAP_SAVE_DIR}/confMat_${TRAIN_EXAMPLES[$tidx]}.txt
		rm ${OMAP_SAVE_DIR}/confMatorg_${tidx}_${vidx}.txt
	done
done

