joint_limits:
  l_gripper_l_finger_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_gripper_l_finger_tip_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_gripper_motor_slider_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_gripper_motor_screw_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  l_gripper_r_finger_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_gripper_r_finger_tip_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_gripper_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_upper_arm_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_forearm_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: true
  l_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  l_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: true
  r_gripper_l_finger_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_gripper_l_finger_tip_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_gripper_motor_slider_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_gripper_motor_screw_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  r_gripper_r_finger_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_gripper_r_finger_tip_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_gripper_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_upper_arm_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_forearm_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: true
  r_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  r_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: true
