planner:
  epsilon: 100
  verbose: false
  use_dijkstra_heuristic: true
  use_research_heuristic: false
  use_uniform_obstacle_cost: false
  use_multiresolution_motion_primitives: false
  obstacle_distance_cost_far: 2
  obstacle_distance_cost_mid: 7
  obstacle_distance_cost_near: 12
  research:
    solve_with_ik_threshold: 0.06
    sum_heuristics: false
    short_distance_mprims_threshold: 0.2
  
robot:
  arm_name: right_arm
  num_joints: 7
  
debug:
  print_out_path: true

visualizations:
  heuristic: true
  goal: true
  expanded_states: false
  trajectory: false
  collision_model_trajectory: false
  trajectory_throttle: 1

collision_space:
  reference_frame: map  # only used in OccupancyGrid to determine frame of red visualization
  resolution: 0.02
  collision_map_topic: collision_map_occ

  occupancy_grid:
    origin_x: -0.6
    origin_y: -1.25
    origin_z: -0.05
    size_x: 1.7
    size_y: 1.9
    size_z: 1.4

reference_frame: map # frame we are planning in
### FOR SUSHI
fk_service_name: pr2_right_arm_kinematics_sushi/get_fk
ik_service_name: pr2_right_arm_kinematics_sushi/get_ik


